export const navigation = [
  {
    id: '0',
    title: 'Home',
    url: '/',
  },
  {
    id: '1',
    title: 'About',
    url: '/about',
  },
  {
    id: '2',
    title: 'Product',
    url: '/product',
  },
]

export const products = [
  {
    id: 1,
    name: 'Réfrigérateur LG',
    href: '/singleproduct',
    category: 'Réfrigérateurs',
    imageSrc: 'https://via.placeholder.com/300?text=Réfrigérateur+LG',
    imageAlt: 'Réfrigérateur LG',
    price: '120000',
    color: 'Silver',
  },
  {
    id: 2,
    name: 'Laveuse Samsung',
    href: '/singleproduct',
    category: 'Laveuses',
    imageSrc: 'https://via.placeholder.com/300?text=Laveuse+Samsung',
    imageAlt: 'Laveuse Samsung',
    price: '80000',
    color: 'White',
  },
  {
    id: 3,
    name: 'Four Bosch',
    href: '/singleproduct',
    category: 'Fours',
    imageSrc: 'https://via.placeholder.com/300?text=Four+Bosch',
    imageAlt: 'Four Bosch',
    price: '60000',
    color: 'Black',
  },
  {
    id: 4,
    name: 'Micro-ondes Panasonic',
    href: '/singleproduct',
    category: 'Micro-ondes',
    imageSrc: 'https://via.placeholder.com/300?text=Micro-ondes+Panasonic',
    imageAlt: 'Micro-ondes Panasonic',
    price: '15000',
    color: 'Black',
  },
  {
    id: 5,
    name: 'Climatiseur Daikin',
    href: '/singleproduct',
    category: 'Climatiseurs',
    imageSrc: 'https://via.placeholder.com/300?text=Climatiseur+Daikin',
    imageAlt: 'Climatiseur Daikin',
    price: '100000',
    color: 'White',
  },
  {
    id: 6,
    name: 'Réfrigérateur Samsung',
    href: '/singleproduct',
    category: 'Réfrigérateurs',
    imageSrc: 'https://via.placeholder.com/300?text=Réfrigérateur+Samsung',
    imageAlt: 'Réfrigérateur Samsung',
    price: '110000',
    color: 'Silver',
  },
  {
    id: 7,
    name: 'Laveuse LG',
    href: '/singleproduct',
    category: 'Laveuses',
    imageSrc: 'https://via.placeholder.com/300?text=Laveuse+LG',
    imageAlt: 'Laveuse LG',
    price: '85000',
    color: 'White',
  },
  {
    id: 8,
    name: 'Four Electrolux',
    href: '/singleproduct',
    category: 'Fours',
    imageSrc: 'https://via.placeholder.com/300?text=Four+Electrolux',
    imageAlt: 'Four Electrolux',
    price: '62000',
    color: 'Black',
  },
  {
    id: 9,
    name: 'Micro-ondes LG',
    href: '/singleproduct',
    category: 'Micro-ondes',
    imageSrc: 'https://via.placeholder.com/300?text=Micro-ondes+LG',
    imageAlt: 'Micro-ondes LG',
    price: '16000',
    color: 'Black',
  },
  {
    id: 10,
    name: 'Climatiseur LG',
    href: '/singleproduct',
    category: 'Climatiseurs',
    imageSrc: 'https://via.placeholder.com/300?text=Climatiseur+LG',
    imageAlt: 'Climatiseur LG',
    price: '102000',
    color: 'White',
  },
  {
    id: 11,
    name: 'Réfrigérateur Bosch',
    href: '/singleproduct',
    category: 'Réfrigérateurs',
    imageSrc: 'https://via.placeholder.com/300?text=Réfrigérateur+Bosch',
    imageAlt: 'Réfrigérateur Bosch',
    price: '115000',
    color: 'Silver',
  },
]
